=== Virihuana/ProyectoXML1/js/validacion2/music.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
      <xs:element name="musica">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="cancion" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
  
      <xs:simpleType name="Titulo">
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
          <xs:maxLength  value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="restriccionAlbum"> 
            <xs:restriction base="xs:string">
              <xs:minLength value="1"/>
              <xs:maxLength  value="150"/>
            </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Album">
      <xs:simpleContent>
        <xs:extension base="restriccionAlbum">
          <xs:attribute name="categoria" type="Categoria"></xs:attribute>
          <xs:attribute name="year" type="Year"></xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="Categoria">
        <xs:restriction base="xs:string">
           <xs:enumeration value="rock"/>
            <xs:enumeration value="indie"/>
            <xs:enumeration value="reggae"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Duracion">
        <xs:restriction base="xs:string">
          <xs:pattern value="([0-9]){2}:([0-9]){2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Year">
        <xs:restriction base="xs:string">
          <xs:pattern value="([1-2])([0-9]){3}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:annotation>
      <xs:documentation xml:lang="es">
          Esta es mi documentacion
      </xs:documentation>
    </xs:annotation>

    <xs:complexType name="tipoSong">
          <xs:all>
                <xs:element name="titulo" type="Titulo"/>
                <xs:element name="album" type="Album"/>
                <xs:element name="duracion" type="Duracion"/>
          </xs:all>
    </xs:complexType>
      
    <xs:element name="cancion" type="tipoSong"/>
</xs:schema>

=== Virihuana/ProyectoXML1/js/validacion2/music.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:///C:/wamp/www/TEMPLATEXML/js/validacion2/music.xsl"?>
<musica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/wamp/www/TEMPLATEXML/js/validacion2/music.xsd">
  <cancion>
      <titulo>Charlie Brown</titulo>
      <album categoria="indie" year="2000">Mylo</album>
      <duracion>04:42452452452445</duracion>
  </cancion>
  <cancion>
      <titulo>Charlie Brown 2</titulo>
      <album categoria="indie" year="2000">Mylo</album>
      <duracion>04:45</duracion>
  </cancion>
  <cancion>
      <titulo>42</titulo>
      <album categoria="rock" year="2001">Viva la Vida</album>
      <duracion>05:12</duracion>
  </cancion>
</musica>
